[project]
title = "lsst-ctrl-bps-panda"

[project.python]
package = "lsst-ctrl-bps-panda"

[build]
clean = true

[sphinx]
extensions = [
    "sphinx_click"
]

[sphinx.intersphinx.projects]
python = "https://docs.python.org/3"
lsst = "https://pipelines.lsst.io/v/daily/"
networkx = "https://networkx.org/documentation/stable/"
